project:
  type: website
  output-dir: docs

website: 
  sidebar: 
    collapse-level: 1
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Python Fundamentals"
        contents:
          - chapter0/softwareCarpentry_PythonFundamentals.ipynb
          - chapter0/softwareCarpentry_AnalyzingPatientData.ipynb
          - chapter0/inflammation-01.csv
      - section: "Chapter 1"
        contents: 
          - chapter1/HoustonTemperatures.ipynb
      - section: "Chapter 2"
        contents: 
          - chapter2/plotBerkeleyEarth.ipynb
          - chapter2/LaurentideIceSheet_and_SeaLevel.ipynb
      - section: "Chapter 3"
        contents: 
          - chapter3/PlancksLaw.ipynb
          - chapter3/RadiationInSpectralBands.ipynb
      - section: "Chapter 4"
        contents: 
          - chapter4/SolarConstant.ipynb
          - InfraredAbsorptionByTheAtmosphere.ipynb

execute: 
  freeze: true

format:
  html:
    toc: true
    theme: cosmo
    css: styles.css
